repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-json
    - id: check-yaml
    - id: check-toml
    - id: check-xml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: trailing-whitespace

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.25.0
    hooks:
    -   id: pyupgrade

-   repo: https://github.com/psf/black
    rev: 21.8b0
    hooks:
    - id: black

-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.1.0
    hooks:
    - id: nbqa-pyupgrade
      additional_dependencies: [pyupgrade==2.25.0]
    - id: nbqa-isort
      additional_dependencies: [isort==5.9.3]
    - id: nbqa-black
      additional_dependencies: [black==21.8b0]
