repos:
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    - id: black

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.11.0
    hooks:
    -   id: pyupgrade

-   repo: https://github.com/nbQA-dev/nbQA
    rev: 0.6.0
    hooks:
    - id: nbqa-black
      additional_dependencies: [black==20.8b1]
    - id: nbqa-pyupgrade
      additional_dependencies: [pyupgrade==2.11.0]
