[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | .eggs
  | build
  | .nox
)/
'''

[tool.nbqa.config]
black = "pyproject.toml"

[tool.nbqa.mutate]
black = 1
pyupgrade = 1
isort = 1

[tool.nbqa.addopts]
pyupgrade = ["--py37-plus"]
