#!/bin/bash

set -e

# Make ROOT available for comparisons and workspace use
# c.f. https://github.com/conda-forge/root-feedstock
conda config --add channels conda-forge
conda config --set channel_priority strict

# Use mamba to speed up install
mamba install --yes root
